//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentDetails.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int ID { get; set; }
        public string Rollno { get; set; }
        public string Stuname { get; set; }
        public string Class { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
        public string Phoneno { get; set; }
        public string Email { get; set; }
        public string Fathername { get; set; }
        public Nullable<System.DateTime> Admissiondate { get; set; }
        public Nullable<System.DateTime> Passedout { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<int> Updatedby { get; set; }
        public Nullable<System.DateTime> Updateddate { get; set; }
    }
}
